---
title: "Putting the R in phaRmacy"
date: "04/12/2020"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(lubridate)
library(fable)
library(tibbletime)
library(feasts)
library(tsibble)
library(sweep)
library(knitr)
library(fable.prophet)
library(pander)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = TRUE, results = "asis")

load("pharmacy.rda")

```

## All sites and drugs {.tabset}

### Drug A

```{r}

drug_code <- "Drug A"

res <- sapply(c("Site A", "Site B", "Site C"), function(x) {
  knitr::knit_child(
    'child.Rmd', envir = environment(), quiet = TRUE
  )
})

cat(unlist(res), sep = '\n')

```

### Drug B

```{r}

drug_code <- "Drug B"

res <- sapply(c("Site A", "Site B", "Site C"), function(x) {
  knitr::knit_child(
    'child.Rmd', envir = environment(), quiet = TRUE
  )
})

cat(unlist(res), sep = '\n')

```

### Drug C

```{r}

drug_code <- "Drug C"

res <- sapply(c("Site A", "Site B", "Site C"), function(x) {
  knitr::knit_child(
    'child.Rmd', envir = environment(), quiet = TRUE
  )
})

cat(unlist(res), sep = '\n')

```

### Drug D

```{r}

drug_code <- "Drug D"

res <- sapply(c("Site A", "Site B", "Site C"), function(x) {
  knitr::knit_child(
    'child.Rmd', envir = environment(), quiet = TRUE
  )
})

cat(unlist(res), sep = '\n')

```
